---
dataset:
 train:
  - /eos/user/a/adpol/suep/SUEPPhysicsSSD_0.h5
 validation:
  - /eos/user/a/adpol/suep/SUEPPhysicsSSD_4.h5
 test:
  - /eos/user/a/adpol/suep/SUEPPhysicsSSD_6.h5
 size:
  - 30000
  - 10000
  - 100000

output:
 model: ./models
 plots: ./plots

training_pref:
 batch_size_train: 50
 batch_size_validation: 50
 max_epochs: 1
 learning_rate: 0.001
 momentum: .9
 patience: 50
 reg_strength: 0.00000000001
 weight_decay: 0.0005
 workers: 0

evaluation_pref:
 batch_size: 50
 names_classes:
  - 't'
  - 'V'
  - 'H'
 workers: 0

inference_pref:
  samples: 300

ssd_settings:
 confidence_threshold: .01
 feature_maps:
  - phi: 46
    eta: 44
  - phi: 24
    eta: 23
 input_dimensions:
  - 1
  - 280
  - 360
 n_classes: 2
 nms: .25
 object_size: 46.
 max_distance: .1
 overlap_threshold: .5
 steps:
  - phi: 8
    eta: 8
  - phi: 17
    eta: 17
 top_k: 100
